export const vaccinesList = [
  {
    id: 1,
    name: "DTaP-IPV-Hib",
    description:
      "Diphtheria, Tetanus, Pertussis, Polio, Haemophilus influenzae type b",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 2,
    name: "Pneu-C-13",
    description: "Pneumococcal Conjugate 13",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 3,
    name: "Rot-1",
    description: "Rotavirus",
    dose: "single",
    type: "mouth",
  },
  {
    id: 4,
    name: "Men-C-C",
    description: "Meningococcal Conjugate C",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 5,
    name: "MMR",
    description: "Measles, Mumps, Rubella",
    dose: "single",
    type: "subcutaneous",
  },
  {
    id: 6,
    name: "Var",
    description: "Varicella",
    dose: "single",
    type: "subcutaneous",
  },
  {
    id: 7,
    name: "MMRV",
    description: "Measles, Mumps, Rubella, Varicella",
    dose: "single",
    type: "subcutaneous",
  },
  {
    id: 8,
    name: "Tdap-IPV",
    description: "Tetanus, diphtheria, pertussis, Polio",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 9,
    name: "HB",
    description: "Hepatitis B",
    dose: "double",
    type: "intramuscular",
  },
  {
    id: 10,
    name: "Men-C-ACYW",
    description: "Meningococcal Conjugate ACYW-135",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 11,
    name: "HPV-9",
    description: "Human Papillomavirus",
    dose: "double",
    type: "intramuscular",
  },
  {
    id: 12,
    name: "Tdap",
    description: "Tetanus, diphtheria, pertussis",
    dose: "single",
    type: "intramuscular",
  },
  {
    id: 13,
    name: "Td_booster",
    description: "Tetanus, diphtheria",
    dose: "multiple",
    type: "intramuscular",
  },
  {
    id: 14,
    name: "HZ",
    description: "Herpes, Zoster",
    dose: "double",
    type: "intramuscular",
  },
  {
    id: 15,
    name: "Pneu-P-23",
    description: "Pneumococcal Polysaccharide 23",
    dose: "single",
    type: "intramuscular/subcutaneous",
  },
  {
    id: 16,
    name: "Tdap_pregnancy",
    description: "Tetanus, diphtheria, pertussis ",
    dose: "multiple",
    type: "intramuscular",
  },
  {
    id: 17,
    name: "Inf",
    description: "Influenza",
    dose: "multiple",
    type: "intramuscular",
  },
];
